### ISSUE TITLE
Use Github Project API for managing Issues

### ISSUE THREAD

**Issue by kordwarshuis** [WebOfTrust/WOT-terms#134]
Github Project API

**Comment by henkvancann** [comment]
- [ ] Action Kor: pull issues in some datastructuur via api as a test in a github action "Roadmap" in WOT-terms repo.
  - [ ] Action Kor: 1 issue in 1 repo (WOT-terms) 1 status change of 1 custom field (Relevance), results in 1 roadmap change in 1 github project.

**Comment by henkvancann** [comment]
https://github.com/WebOfTrust/keri/discussions/78 this how they currently discuss it during the Thu - calls. 
LoE: Level of Effort

**Comment by kordwarshuis** [comment]
Move functionality from dwarshuis.com to Heroku

**Comment by henkvancann** [comment]
https://github.com/WebOfTrust/keri/discussions/78 -> I have joined a few meetings using this page. What could be handy:
- [ ] voting about the importance of an issue (the top-down ordering) - Now the leader asks repetitively "is the order OK??!", nobody answers.

**Comment by henkvancann** [comment]
onhold
