### ISSUE TITLE
Typesense

### ISSUE THREAD

**Issue by kordwarshuis** [WebOfTrust/WOT-terms#135]
Research how to have multiple Collections in Typesense.

**Comment by kordwarshuis** [comment]
Action Kor: Ask Jason Bosco-Typesense : exclude from - or lower in the search results based on field values (for example: the field called “source” with value “KERISSE (this site)” a lower preference in the search results?) Henk: YES, good idea!

**Comment by kordwarshuis** [comment]
Typesense config: search for 'verify' in glossary using general Search should list 'verify' in the glossary first.

**Comment by henkvancann** [comment]
- [ ] Action - Henk: 1 search query + prefered results incl. ranking. E.g. Howto launch a KERI witness.

**Comment by kordwarshuis** [comment]
Continue in https://github.com/WebOfTrust/WOT-terms/issues/75 ?

**Comment by henkvancann** [comment]
onhold and indeed related to  https://github.com/WebOfTrust/WOT-terms/issues/75
