### ISSUE TITLE
Split terms definitions into single files

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/WOT-terms#145]
REPO: https://github.com/blockchainbird/spec-up-t/

The repo is the main glossary of ToIP has all its definitions in one file, organised by spec-up.

This creates various inpracticalities. The new design is here ->

 
![Screenshot 2024-04-08 at 13 59 20](https://github.com/WebOfTrust/WOT-terms/assets/479356/65861a8a-d6b9-41c0-ad77-01d27dcbb600)

Main points:
- git(hub) commits needed (for tracking and versioning)
- choice of source management of term definitions: vscode, wiki, plain github file edit, etc

**First step is to split up** the file  [terms_and_definitions.md](https://github.com/trustoverip/ctwg-main-glossary/blob/main/spec/terms_and_definitions.md) in a directory called terms_and_definitions under the spec dir of the repo.

The result is:

### In the directory terms_and_definitions
 we'll find the the single files {term}.md with the spec-up [[def : ]] and [[ ref : ]]s and [[ xref : ]]s.

### Specs.json
terms_and_definitions.md -> terms_and_definitions/{term}.md for all terms _in a certain order_ added to specs.json below the entry terms_and_definitions.md. The default order is alphabetically.

**Comment by henkvancann** [comment]
https://dwarshuis.com/test/spec-up-ctwg/#terms-definitions

In this demo, it would be good to have persistent anchors to every term.

**Comment by henkvancann** [comment]
persistent anchors done, specs.json must still be reengineered:

Specs.json
terms_and_definitions.md -> terms_and_definitions/{term}.md for all terms in a certain order added to specs.json below the entry terms_and_definitions.md. The default order is alphabetically.

**Comment by kordwarshuis** [comment]
Done, see https://github.com/WebOfTrust/WOT-terms/issues/199
