### ISSUE TITLE
Roadmap of KERI and ACDC and go to place for a status report

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/WOT-terms#16]
Roadmap It’s important to realize this is about **the KERI / ACDC roadmap** and not our own roadmap in the Concepts-Terms-Edu group. 

There is a central location or jump-off spot in the KERI repo; the README: https://github.com/WebOfTrust/keri

There's demand for a more detailed and accurate roadmap and continuous status report with links the right locations where (re)sources can be found.

Topics that are interesting in the approach to document this:
(Discussed Aug 25 2022 during Meetup)

1. Ruth: What is and what is not implemented : Watcher service (Not), revocation (is, but not working)
2. Joseph: where are we, so I could recommend certain parts or applications of KERI
3. Steven: what’s GLEIF and what’s KERI?
4. Kent: focus on Key management in the roadmap (+ storage / rotation )
5. Kent: 3 stages: familiar with KERI -> easy CLI to demo -> to do a basic reference implementation
6. Steven: 3 usecases for what hasn’t been created yet: what would you do with KERI if you had it?

This is the hackedmd.io file to start off with: https://hackmd.io/yYpd2uhRTpCadsGVw3Rl-A

**Comment by henkvancann** [comment]
We discussed and improved the ToC of the envisaged roadmap: https://hackmd.io/yYpd2uhRTpCadsGVw3Rl-A

**Comment by kordwarshuis** [comment]
Accidentally closed

**Comment by henkvancann** [comment]
## 2023 - 2024 brainstorm

Roadmap - visualisation KERI Suite : dependencies between issues and between Versions (Breaking changes y/n) + UI, NUI, NIU, NINU - only consistency checks, no AI.

Action items: 

https://hackmd.io/@hvancann/S1mvMkEk3?type=view#2024-01-11

https://hackmd.io/@hvancann/S1mvMkEk3?type=view#2024-01-04

**Comment by henkvancann** [comment]
onhold
