### ISSUE TITLE
Running Github Actions simultanously can give error

### ISSUE THREAD

**Issue by kordwarshuis** [WebOfTrust/WOT-terms#163]
Example
Running “Import metadata from Google Sheets” and “Import Wiki” generates error.

**Comment by kordwarshuis** [comment]
Action step 1:
Start several actions at the same time and see if it errors again (maybe it was a github disruption).

**Comment by kordwarshuis** [comment]
Test: running Deploy to Github Pages and Find broken links at the same time
==> Works. No error.

**Comment by kordwarshuis** [comment]
Test: running Import external glossaries and Import metadata from Google Sheets at the same time
==> Import external glossaries crashes.

**Comment by kordwarshuis** [comment]
chatGPT: add this before you pull:

```
    {
      git pull --rebase
    } || {
      echo "Rebase failed, aborting rebase."
      git rebase --abort
      echo "Retrying with merge."
      git pull --no-rebase
    }
```

See https://chatgpt.com/share/a49feeec-6bde-4d05-858e-10009dee6a4d

**Comment by henkvancann** [comment]
Ask Stackoverflow? Or a git forum?

**Comment by kordwarshuis** [comment]
See https://github.com/WebOfTrust/WOT-terms/issues/184 for the solution.
