### ISSUE TITLE
Create redirects

### ISSUE THREAD

**Issue by kordwarshuis** [WebOfTrust/WOT-terms#174]
kerisse.org ==> https://weboftrust.github.io/kerisse/

glossary.kerisse.org ==> https://weboftrust.github.io/WOT-terms/

search.kerisse.org ==> https://weboftrust.github.io/kerisse/

doc.kerisse.org ==> https://weboftrust.github.io/keridoc/

**Comment by henkvancann** [comment]
Delegate to Digistate, we sort of pay for this service.

**Comment by kordwarshuis** [comment]
Yes, forgot to say the ticket has been created at Digistate.

**Comment by kordwarshuis** [comment]
Probably also create:

keridoc.kerisse.org ==> https://weboftrust.github.io/keridoc/

**Comment by kordwarshuis** [comment]
Digistate reply raises new question. To be continued.

**Comment by kordwarshuis** [comment]
Done.
Documented here: https://weboftrust.github.io/keridoc/docs/how-we-did/general/redirects
