### ISSUE TITLE
Digistate reply raises new question. To be continued.

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/WOT-terms#175]
Digistate reply raises new question. To be continued.

_Originally posted by @kordwarshuis in https://github.com/WebOfTrust/WOT-terms/issues/174#issuecomment-2232995821_
            
If it's relevant pls copy both the essence of their reply and your new question

**Comment by henkvancann** [comment]
you can close this new issue when read and done

**Comment by kordwarshuis** [comment]
This is a summary of their reply:

https://weboftrust.github.io/keridoc/docs/how-we-did/general/redirects/
