### ISSUE TITLE
Link generation after parsing a raw text with a list of terms

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/WOT-terms#18]
A question you might know a direction of an answer to

henkvancann
  [9:08 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665428934871509)
Based on a count of terms in a text or md file (e.g. a raw version of a whitepaper) I’d like to generate links into the text of that file.
So I have a two column list of terms and their links to the glossary and then a text is parsed to count the terms. And now I’d like to create a link on every N-th occurrence of all the terms (that doesn’t have a link yet), whereby N = Count / Divider, starting from the top of the document.
Question: have you ever seen someone has done it before?
New

Sid Haniff
  [9:10 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429037316019)
I haven’t no but what are you using to do the parsing?

henkvancann
  [9:11 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429066379799)
sed and awk
[9:11](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429080715299)
e.g.
:relaxed: cat testRL.txt                                                          gh-pages ✗
self-certifying identifier is a hash thing to escrow
public transaction event logs are [nasty](nasty) and http://event.com/public/transaction.md
[9:11](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429098715709)
#!/bin/bash
# Purpose: Test link replacement with variables
# Author: Henk van Cann
linky=“http://hier.komt.wat/nogiets.html”
tterm=“self-certifying identifier”
sed -r “s|(${tterm})+|[\1](${linky})|g”  testRL.txt

Sid Haniff
  [9:12 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429138639039)
Ah I’ll have a look tomorrow … I’m logged off my computer now and just reading this on the phone

henkvancann
  [9:12 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429140093949)
Output:
[self-certifying identifier](http://hier.komt.wat/nogiets.html) is a hash thing to escrow
public transaction event logs are [nasty](nasty) and http://event.com/public/transaction.md
[9:13](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429204167359)
Pls don’t feel obliged, I just don’t like to reinvent wheels

Sid Haniff
  [9:13 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429230633789)
No sure it sounds interesting and happy to have a look / think

henkvancann
  [9:16 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429377437789)
This tool is the hardest last linking pin to get my head around and then I should be able to generate a text that contains many links to a glossary because a fuzzy search has found the links to it in raw plain text. From this I’d like to generate the sidebars as well like this example here: http://127.0.0.1:4000/WOT-terms/mydoc_about_ruby_gems_etc.htmlA question you might know a direction of an answer to

henkvancann
  [9:08 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665428934871509)
Based on a count of terms in a text or md file (e.g. a raw version of a whitepaper) I’d like to generate links into the text of that file.
So I have a two column list of terms and their links to the glossary and then a text is parsed to count the terms. And now I’d like to create a link on every N-th occurrence of all the terms (that doesn’t have a link yet), whereby N = Count / Divider, starting from the top of the document.
Question: have you ever seen someone has done it before?
New

Sid Haniff
  [9:10 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429037316019)
I haven’t no but what are you using to do the parsing?

henkvancann
  [9:11 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429066379799)
sed and awk
[9:11](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429080715299)
e.g.
```
:relaxed: cat testRL.txt                                                          gh-pages ✗
self-certifying identifier is a hash thing to escrow
public transaction event logs are [nasty](nasty) and http://event.com/public/transaction.md
```

[9:11](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429098715709)
```
#!/bin/bash
# Purpose: Test link replacement with variables
# Author: Henk van Cann
linky=“http://hier.komt.wat/nogiets.html”
tterm=“self-certifying identifier”
sed -r “s|(${tterm})+|[\1](${linky})|g”  testRL.txt
```

Sid Haniff
  [9:12 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429138639039)
Ah I’ll have a look tomorrow … I’m logged off my computer now and just reading this on the phone

henkvancann
  [9:12 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429140093949)
Output:
[self-certifying identifier](http://hier.komt.wat/nogiets.html) is a hash thing to escrow
public transaction event logs are [nasty](nasty) and http://event.com/public/transaction.md
[9:13](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429204167359)
Pls don’t feel obliged, I just don’t like to reinvent wheels

Sid Haniff
  [9:13 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429230633789)
No sure it sounds interesting and happy to have a look / think

henkvancann
  [9:16 PM](https://trustoverip.slack.com/archives/D03PU2ES74N/p1665429377437789)
This tool is the hardest last linking pin to get my head around and then I should be able to generate a text that contains many links to a glossary because a fuzzy search has found the links to it in raw plain text. From this I’d like to generate the sidebars as well like this example here: http://127.0.0.1:4000/WOT-terms/mydoc_about_ruby_gems_etc.html

**Comment by sih** [comment]
Do you have an interim list where the terms are ordered? If so I wonder if you could use a modulo operator in awk to put a link on every Nth occurrence, i.e. where count%N == 0. I'm no awk expert so it's just a thought

**Comment by henkvancann** [comment]
Yes, I have pairs "in hand": term-link. And I do a fuzzy search on them (which is another challenge: how to not replace a term that already is part of another link or even a better matching link down the road.
Examples:
`[abc](http://abc.com)d` should not be replaced by cd - http://cd.io pair
`abcd` should not be replaced by ab - http://ab.uk.co pair when I have a better matching abc - http://abc.com somewhere in the list of pairs.

**Comment by henkvancann** [comment]
The pseudo - code I've created so far:

#!/bin/bash
# Purpose: TEXT selective link replacement with variables, on the basis of RULES, a LIST of terms 
# and a POPUP description file with terms.
# Author: Henk van Cann
# Arguments: 
## firstN = is number of free and raw terms in text to replace with popup and link. Free means no link yet.
## ModM = is number of visible terms to skip, replace every M'th visible word after N in the text.
# Make/Take LIST.txt: term, link, description, level, cat_*
## Filter lenght(term), level>lev, cat in cat_*

# Check internal consistency LIST.txt, make unique on terms
# Make/Take POPUP.yml: term, description
# Check internal consistency POPUP.yml, make unique on terms
# Optional - Check external consistency LIST.txt and POPUP.yml: popup contains at least all popup terms
# Sort LIST on length term and then alphabeth
# Pull TEXT through localizer: and find replace links with "term_*"
# RULES:
## match reserved word list with TEXT and mark+markcount 
## linkurl * is href="*",  ](*), http://* , https://* 
## linktxt @ is >@</a> [@](
## text in linkurl -> mark, don't replace
## text in linktxt -> mark, don't replace, but markcount
## text in raw -> mark, replace, markcount
## replace firstN "free" occurrence of term
## replace ModM "free" occurrence of term

# Per LIST all terms
## Per term
## if searchterm not in POPUP.yml, skip term
## Check for existing marking 
## if mark >= current process then error
## start counting searchterm
## if mark contains searchterm in linktxt then 
### if linktxt == searchterm -> error 
## markcount++
## markreplace firstN, ModM
## replace

# Per TEXT after all terms in LIST processed
## remove all markers

**Comment by henkvancann** [comment]
not relevant anymore in Docusaurus
