### ISSUE TITLE
Introduce Collections in Typesense and add correct filters 

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/WOT-terms#75]
To do Kor/Henk design: "show Type filter *only for* the glossary", glossary could have its own Typesense collection which would then also show the correct filters, so all others would not show "Type" filter.
The UI of the SE could offer these buttons for the various collections.
[All] (default) [Glossary only] [KERISSE only] [BLOGs only] [Whitepapers only].
A Typesense collection should keep track of its relevant filter-options.

**Comment by kordwarshuis** [comment]
Is this still relevant now that we have kerisse, keridoc and keriglos?

**Comment by henkvancann** [comment]
Yes, it's still relevant because you'd like to limit/filter the search results from kerisse.org (the SE) with these buttons.
