### ISSUE TITLE
KERI Suite Feedback: 

### ISSUE THREAD

**Issue by trent-medici** [WebOfTrust/WOT-terms#77]
### How did you hear about KERI Suite?

at IIW

### Which part of the KERI Suite was your angle to look for?

- [ ] key management
- [ ] crypto currency
- [X] Self Sovereign Identity
- [ ] KERI
- [ ] ACDC
- [ ] CESR
- [ ] OOBI
- [ ] IPEX
- [ ] PTEL
- [ ] KERIA
- [ ] SIGNIFY

### What was the point of interest for you as a developer?

Beyond the comprehensive key management, the ACDC spec and other conversations show that this can be the foundation for secure data across a range of interoperable deployments (ie. simple building blocks that are not dependent on advanced cryptography).

### Why did you become involved?

I want to build systems to generate credentials in an interoperable way.

### How did you become involved?

Slowly, after seeing it at IIW a few times and hearing the discussions on calls and seeing other skilled, trusted people work on it.

### How did you build up you knowledge?

Again, slowly: getting the system running with Kent Bull's (personal) assistance, reading and referencing the specs multiple times, lurking on calls.

### How did you build up your skills?

I can't say I have many yet, but I want to experiment with the pieces (eg. generate CESR, generate some keys and sign and validate, generate ACDCs and validate).

### What learning resources lacked?

Broken codebases. (At one point I was able to run keria & signify and test, but then that broke and IPEX was introduced as a necessity... and some people pointed my to specific commits that would work and I hear things work now but I haven't had the time and motivation to try again.)

### What tips & tricks would you have for us?

I would put the "work through tutorials" first (unless the "introductory reading" is a single blog post that points to tutorials). We learn by doing, and that educational progression through the concepts is a tough presentation to create but would be immensely valuable.

**Comment by henkvancann** [comment]
We'll use all the KERI Suite Feedback for a larger upgrade planned this spring / summer. Thanks!
