### ISSUE TITLE
KERI Suite Feedback: 

### ISSUE THREAD

**Issue by kentbull** [WebOfTrust/WOT-terms#79]
### How did you hear about KERI Suite?

other

### Other Source

Self Sovereign Identity book by Drummond Reed and Alex Preschaut

### Which part of the KERI Suite was your angle to look for?

- [X] key management
- [ ] crypto currency
- [X] Self Sovereign Identity
- [ ] KERI
- [ ] ACDC
- [ ] CESR
- [ ] OOBI
- [ ] IPEX
- [ ] PTEL
- [ ] KERIA
- [ ] SIGNIFY

### What was the point of interest for you as a developer?

I wanted to know how to build a secure identity system for a digital currency. Not necessarily a crypto currency, a central bank digital currency.

### Why did you become involved?

I became involved because KERI solves the problem I had and inspired me to master it. It is simple and easy to understand and fit in my head. I like the layered protocols approach rather than having to buy into the governance of any specific network or network architecture like so many other SSI, decentralized identity, or blockchain platforms do.

### How did you become involved?

I started attending KERI meetings and went to IIW for the first time in Oct 2021.

### How did you build up you knowledge?

Going to meetings, reading source code, trying to build things, reading through and playing with the Bash scripts testing out the KLI and agent.

### How did you build up your skills?

Reading through source code, starting and chairing the CESR working group for a while, going to weekly meetings, writing a blog post, going to IIW and presenting about KERI.

### What learning resources lacked?

I lacked an easy to use demo of the tech connected to a user interface. I also lacked an overview of key concepts aimed at developers anchored to the tech demo.

Beyond the initial learning there are also things lacking to bring one up to speed with the current state of the codebase as compared to the whitepaper. There is a beginning of, yet not enough of, blog posts and technical guides on the architectural choices, code design, and implementation choices in KERIpy, KERIA, SignifyTS, and CESRide.

### What tips & tricks would you have for us?

First start with a demo using an open source wallet. That makes everything else so clear. The demo needs to include the connection setup with OOBIs, the challenge phrase process, and the issue, hold, verify ceremony. People need to believe it works and that it works easily. The working demo opens the way for curiosity and further learning by giving people a strong base to experiment from.

Make the introductory reading less than 5 pages, use lots of pictures, and get the basic KERI network up and running quickly. Otherwise it becomes hard to anchor the knowledge for anyone who isn't highly motivated and incentivized to learn.

**Comment by henkvancann** [comment]
We'll use all the KERI Suite Feedback for a larger upgrade planned this spring / summer. Thanks!
