### ISSUE TITLE
KERI Suite Feedback: 

### ISSUE THREAD

**Issue by edeykholt** [WebOfTrust/WOT-terms#88]
### How did you hear about KERI Suite?

at IIW

### Which part of the KERI Suite was your angle to look for?

- [X] key management
- [ ] crypto currency
- [X] Self Sovereign Identity
- [X] KERI
- [X] ACDC
- [ ] CESR
- [ ] OOBI
- [ ] IPEX
- [ ] PTEL
- [ ] KERIA
- [ ] SIGNIFY

### What was the point of interest for you as a developer?

To understand why there is momentum behind it (relative to W3C VCs and other technologies) and understand why and how technically it claims to solve problems around, e.g. key pre-rotation, no big VDR required, root-of-trust, better serialization/deserialization.

### Why did you become involved?

To help make the internet more trustworthy and to explore business / income opportunities around that mission.

### How did you become involved?

Attended IIW sessions. Talked with a few people already involved, who suggested where given my skills and interests I might best contribute. Joined ToIP.

### How did you build up you knowledge?

1. IIW presentations; 2. Sam Smith's KERI Whitepaper; 3. Kent Bull's walkthrough video and blog.

### How did you build up your skills?

For KERI specifically (vs SSI in general), Kent Bull's walkthrough was very helpful.  Still building skills.

### What learning resources lacked?

Diagrams of how the specs relate to (depend on) each other, and diagrams of how the implementation projects relate to each other.

### What tips & tricks would you have for us?

The above is good for a developer who wants to contribute to the project components and understand deeply. I haven't completed the list yet.  Ideally, I'd like to more simply use these components to build applications, so some clarity of what can be built with today's infrastructure would be helpful.  Sample end-to-end solutions, even if they are "just" e2e integration test scripts with a recent docker container, would be very helpful for application developers.
I also happen to learn visually and motivated to understand how systems need to interconnect to form a solution. I often sketch component dependency diagrams, UML Class Diagrams (as I've done for the TSP), and State Diagrams (as I've done for the IPEX protocol).  These types of diagrams, even if just conceptual level, would help some others whose "native" language isn't at the code level.

**Comment by henkvancann** [comment]
You might find diagrams in the slack history. There's no good way to search. Just scrolling up and down in channel is pretty quick.
We're interested in the results (diagrams) of your work to include in kerisse.org or in Q&As

**Comment by henkvancann** [comment]
We'll use all the KERI Suite Feedback for a larger upgrade planned this spring / summer. Thanks!
The diagramming has started, as you've seen :)
