### ISSUE TITLE
Kerific did not pick the following words:  KERI, ACDC, DID, Delegation, Revocation, (Pre)Rotation, ...

### ISSUE THREAD

**Issue by rc-provenant** [WebOfTrust/WOT-terms#98]
Kerific did not pick the following words:  KERI, ACDC, DID, Delegation, Revocation, (Pre)Rotation, ...

**Comment by kordwarshuis** [comment]
Hi, thanks for your observations, that's really helpful. You are right. I am working on a fix.

**Comment by rc-provenant** [comment]
You're very welcome.  I think the tool is awesome!

**Comment by kordwarshuis** [comment]
I am a bit late, but thanks @rc-provenant !
I think it's fixed now.
